### PR TITLE
Collection modification via transformResponse

### LINKED ISSUE #64: Collection Modification on pagination:loadPage
Hello,

I've been through the issues here and came across #19 which had a couple comments about collection modification.  As @dnauck mentioned, sometimes there are instances where UI related components require some data manipulation prior to display.

A simple use case I've come up against recently is the requirement to calculate a duration based on a start and end time.  I achieve this currently by calling out to a method on a per record basis, but it would be nice to iterate over the collection after it was loaded and extending my object with my "duration" property.

I know you mentioned the possibility of adding a "transformResponse" parameter at the bottom of #19.

Any further thoughts here?  Thank you.

### PR DESCRIPTION
**Pull request by bjubinville**
Closes #64.

### CODE REVIEW

**Comment by begriffs** [comment]
That was amazingly fast! Can you add a note to the docs as well about this?

**Comment by bjubinville** [comment]
@begriffs updated.

**Comment by bjubinville** [comment]
@begriffs is this ok to go?

**Comment by begriffs** [comment]
Oh thanks for reminding me. I did have one thought: is it necessary to reset to page 0 when changing the transformation function? For instance if my function was to uppercase the words and I remove the transform it seems to me the pagination could remain on the current page but go back to its original case.

**Comment by bjubinville** [comment]
I thought that was a little wonky personally, but wanted to be consistent.  I can think of instances where you may want to add additional UI elements that would manipulate the callback potentially, but I’m easy either way.

**Comment by begriffs** [comment]
Are you saying it feels wonky for the page to reset to 0 when changing any of the properties, or only when changing the transformation function?

**Comment by bjubinville** [comment]
The fact we can’t actually compare if the function truly “changes” is wonky.  That said, I would advocate for keeping it as is for now.  My 2c.

**Pull request merged**
