### PR TITLE
Ability to provide callback function to search and trigger a reload from the controller

### PR DESCRIPTION
**Pull request by marcoschulte**
We needed the ability to further customize the http request and transform the reponse, so we introduced a new param to the directive to provide a callback.
We also needed to trigger a reload, so we added a new event.

The callback gets the http config to have all parameters like the range at hand and needs to return a promise.

This is how one could use the directive:

```html
<button ng-click="reload()">Reload results</button>
<bgf-pagination collection="data" page="filter.page" per-page="filter.perpage" load-fn="callback(config)"></bgf-pagination>
```

```javascript
// controller
$scope.reload = function () {
    $scope.$broadcast('pagination:reload');
}

$scope.callback = function (config) {
    return $http(config);
}
```

Alternatively
```javascript
// controller
$scope.callback = function (config) {
    return $q(function (resolve) {
            resolve({
                data: ['a', 'b'],
                status: 200,
                config: {},
                headers: function (headerName) {
                    // fake Content-Range headers
                    return '0-1/*';
                }
            });
        }
    );
}
```

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks for creating a pull request for your improvements (with tests and everything)!

Can you explain more about the use case which requires the extra callbacks?

**Comment by marcoschulte** [comment]
Yes, sure. We are wrapping the $http object with a service which handles all server calls.

The service exists for several reasons:
* The app we are bundling is environment independent. We have a mechanism to provide the server's url from outside. We didn't want the url to be cluttered around our app but instead one single point where the endpoint is determined - in our service. Therefor we didn't want to set the url attribute on the directive.
* All respones from our api are wrapping the actual result with meta information/notifications/alerts that might need to be displayed, etc. The service is taking care of handling these information and strips them from the actual result, which is then passed down to the service's invoker. Therefor we don't have the handling of these information in scattered in every controller.
* We are enriching the requests with more headers (api token). We didn't want to use http interceptors as this felt like too much magic in our opinion and wanted to be able to replace $http with a different rest provider.

To use this service there was no other way than to be able to specify a callback function.

**Comment by begriffs** [comment]
This seems like an approach which may be nonstandard for Angular, but your change looks backwards compatible so it should be OK. Can you add documentation about these new features to the readme please? After that I'll merge your change, bump the minor version and publish the new package.

**Comment by marcoschulte** [comment]
That's great news, thanks! The documentation is edited.

Just out of curiosity, and as we have a very strong Java EE background - why would you consider this as nonstandard for Angular?

**Comment by begriffs** [comment]
The other code examples on the readme use the convention of two spaces per indentation level, could you adjust yours please?

About the standard Angular question, I guess I don't know whether or not these changes are "nonstandard." I have been out of touch with the Angular world for several years now.

**Comment by marcoschulte** [comment]
Sorry, you're right. I corrected the indentation.

Thanks again.

**Comment by begriffs** [comment]
I released v0.4.2

**Comment by marcoschulte** [comment]
Thanks a lot 👍

**Pull request merged**
