### PR TITLE
Added optional parameters getDataFn and getDataFnContext

### PR DESCRIPTION
**Pull request by nuba**
Hello @begriffs,

I had to stick to angular services to reach our API endpoints in a large project (a lot of tweaks here are done at .config() time to adjust for dev/stage/production environments).

I could successfully stick to angular-paginate-anything :) with the small fix in this PR, which also addresses #42 by @stephaneeybert. Can you please review it? If it's something you'd like to merge, I'd be happy to make it more generic and documented. Let me know!

Best Regards,

Nuba

BTW this is how I use it in my template (jade)
 ~~~jade
    bgf-pagination(
      collection="vm.manyThings"
      url="vm.paginateAnythingParams.url"
      url-params="vm.paginateAnythingParams.urlParams"
      get-data-fn="vm.paginateAnythingGetData"
      get-data-fn-context="vm"
    )
~~~

and in my code (typescript)

~~~ts
    public paginateAnythingGetData(httpReqConfig) {
      // this is what angular-paginate-anything-does
      // return $http(httpReqConfig);

      // myApiService.apiMethod returns $http(...) too, so we're good
      return this.myApiService.apiMethod(
          httpReqConfig.params.foo,
          httpReqConfig.params.bar,
          httpReqConfig.headers['Range'],
          httpReqConfig.headers['Range-Unit'],
          this.cacheKey
    );
~~~

### CODE REVIEW

**Comment by begriffs** [comment]
Looks like a good idea to make the library more flexible. If you provide good docs for the feature and ensure it's backwards compatible (i.e. omitting `get-data-fn` acts the same), and add a test then it should be good to add!

Thanks for taking the time to contribute back to the project.

**Comment by begriffs** [comment]
(bump)

**Comment by nuba** [comment]
I'll look into it this week! :)

**Comment by begriffs** [comment]
Hey the master branch test suite has been fixed! If you're still interested in sending this PR please rebase off the new master.

**Comment by begriffs** [comment]
Looks like you deleted your fork of this project so I'm going to close this pull request. Feel free to open it again if you'd like to complete the documentation.

**Pull request closed without merging**
