### PR TITLE
ES6 import/require Support

### PR DESCRIPTION
**Pull request by brunowego**
👍

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks! Is this compatible with pre ES6 code as well?

**Comment by brunowego** [comment]
This works when import in ES6 code:

```js
import angular from 'angular';
import Paginate from  'angular-paginate-anything';

const Root = angular
  .module('app', [
    Paginate
  ])
  .name;

export default Root;
```

**Comment by begriffs** [comment]
Do I need to release a new version so that you can pick up the changes?

**Comment by brunowego** [comment]
Yes, but let me try some tests first.

**Comment by brunowego** [comment]
I made a mistake, there is an important question about its implementation. If the user only imports the library, it will somehow need to load the template as well.

If the user is using webpack, they can include the html as a template.

Or, we can include [paginate-anything-tpls.js](https://github.com/begriffs/angular-paginate-anything/blob/master/dist/paginate-anything-tpls.js) instead.

**Comment by brunowego** [comment]
Works nicer now #101

**Pull request merged**
