### PR TITLE
Build is no longer failing

### PR DESCRIPTION
**Pull request by eidsonator**
Moved parseRange and length functions towards top of the file so jshint will pass.

Check passive parameter at the beginning of the requestRange function to stop the http request from being sent if there is a passive parameter is set to 'true'.  This allows the "passive mode prevents duplicate loading" test to pass.

### CODE REVIEW

**Comment by begriffs** [comment]
I really appreciate this PR, thank you! I'll examine it in more detail and merge tomorrow or the next day. I may want to release a new version too since this will fix the bug in passive mode.

**Comment by begriffs** [comment]
Yeah this looks great, merging! 😎

**Comment by eidsonator** [comment]
Great, I'll be sending another one soon.  I found another (small) bug when
trying to use a scope variable for the url.

Thanks!
Todd

**Comment by begriffs** [comment]
OK, after merging the next one I'll bump the patch version. Sound good?

**Comment by eidsonator** [comment]
It looks like you got those changes already, as well.  Bump away!

Thanks.

**Pull request merged**
